[package]
name = "echor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {workspace = true, features = ["derive"]}

[dev-dependencies]
anyhow = {workspace = true}
assert_cmd = {workspace = true}
predicates = {workspace = true}
pretty_assertions = {workspace = true}